### ISSUE TITLE
Patch for uml tools to work in Ubuntu

### ISSUE THREAD

**Issue by kartoch** [maxonthegit/netkit-core#13]
The last release includes this change:

```
uml-utilities have been recompiled with dynamic linking and with Ubuntu
patches applied. This makes them work also under Ubuntu 10.10. Moreover,
uml_mconsole now also looks inside $HOME/.uml for management console sockets.
```

Is that possible to have this patch, as I need to compile uml_tools again for uml_dump support ?

**Comment by maxonthegit** [comment]
If you mean the Ubuntu patch, it's in the [Ubuntu repos](http://archive.ubuntu.com/ubuntu/pool/universe/u/uml-utilities/). You can retrieve it using `apt-src` or just access the following links:
http://archive.ubuntu.com/ubuntu/pool/universe/u/uml-utilities/uml-utilities_20070815.orig.tar.gz
http://archive.ubuntu.com/ubuntu/pool/universe/u/uml-utilities/uml-utilities_20070815-1.1ubuntu2.dsc
http://archive.ubuntu.com/ubuntu/pool/universe/u/uml-utilities/uml-utilities_20070815-1.1ubuntu2.diff.gz
