### ISSUE TITLE
lhalt and vhalt don't work

### ISSUE THREAD

**Issue by PabloPerdomo** [maxonthegit/netkit-core#15]
If I run lhalt or vhalt it tries to halt the lab or vm don't work and display this message:
vhalt: could not shut down virtual machine "pc1".
So I need to run shutdown -h now for each vm. If is a lab then is obtrusive.

In case to be needed:
=> uname -a gives Linux myhost 2.6.38-ARCH #1 SMP PREEMPT Mon May 23 22:02:08 CEST 2011 x86_64 Intel(R) Core(TM)2 Duo CPU T5550 @ 1.83GHz GenuineIntel GNU/Linux
=> I installed lib32-glibc (2.13-15) from multilib to exec 32 bits apps.

Thanks.

**Comment by maxonthegit** [comment]
This is likely due to a (currently undocumented) dependency of `uml_mconsole` from the 32-bit version of `libreadline`. And `uml_mconsole` is required to properly halt virtual machines.

You can easily work this around by installing the `lib32readline6` package, but maybe we'd better document this.

**Comment by PabloPerdomo** [comment]
Thanks. Now work fine.
