### ISSUE TITLE
New versions of Quagga

### ISSUE THREAD

**Issue by medim** [maxonthegit/netkit-core#27]
Hi,

Have you tried tried to install the new versions of quagga (eg. quagga-0.99.21) on the a VM (with kernel netkit-kernel-i386-K2.8).
Actually, after the installation no matter what module I enable in daemon I get the following error, for example for zebra:

Starting Quagga daemons (prio:10): zebra/sbin/zebra: symbol lookup error: /sbin/zebra: undefined symbol: smux_init

Sorry if the question is irrelevant, honestly I have not tried it on my local machine and I am not sure if it was related to quagga.
If it is a know issue and no solution, I was wondering if you could suggest the latest compatible version of quagga for Netkit (because the already installed one is quite old)

Cheers
Mehdi

**Comment by maxonthegit** [comment]
Hi,

here is a successful upgrade sequence:
1. (host-side) `vstart pc1 --eth0=tap,10.0.0.1,10.0.0.2 --mem=256`
2. (copy your host's `/etc/resolv.conf` to the virtual machine)
3. `sed -i '/^smux/d' *.conf`
   (clears any SNMP-related statements from configuration files, as specified by Debian documentation)
4. `apt-get update`
5. `apt-get install -y --force-yes quagga`
   (you can go with default answers)
6.  

```
pc1:/etc/quagga# /etc/init.d/quagga restart
Stopping Quagga daemons (prio:0): zebra (bgpd) (ripd) (ripngd) (ospfd) (ospf6d) (isisd) (ldpd).
Removing all routes made by zebra.
Nothing to flush.
Loading capability module if not yet done.
Starting Quagga daemons (prio:10): zebra.
pc1:/etc/quagga# ps aux | grep zebra
quagga    1952  0.0  0.4   5120  1204 ?        Ss   13:22   0:00 /sbin/zebra --daemon -A 0.0.0.0
root      1954  0.0  0.2   3776   712 tty0     S+   13:22   0:00 grep --color zebra
```

Once again, this is more a Debian-related doubt than an actual Netkit issue, so I suggest submitting and discussing further similar problems using Netkit mail contacts (the mailing list or contact@netkit.org).

Please confirm that this closes the issue.

Regards,
Massimo

**Comment by medim** [comment]
Hi,

Thank you very much, the issue was solved, and as you said it was debian issue, and in addition to what you have suggested, I needed to install snmpd and libsnmp-dev as well.

Thanks,
Mehdi

**Comment by maxonthegit** [comment]
Right. I also forgot to mention that there are also ways to still enable SNMP, but this may require a bit more work and I'm assuming you are not interested at this time.

So, I'm closing the issue.

**Comment by medim** [comment]
Yes right, I'm mostly into BGP/network modelling. BTW many thanks for your great and early support.
Mehdi
